/*----------------------------------------------------------------------------------
 SQL DB
----------------------------------------------------------------------------------*/
#ifndef _SQLDB_H_
#define _SQLDB_H_

//¹Î¿øÄÚµå

#define AssignKeyCnt 	1
#define AssignUCnt 		103
#define AssignICnt 		106

FieldInfo m_stMwAssignKey[AssignKeyCnt] =
{
{ "promise_assign_seq", "promise_assign_seq", SQLITE_INT, DECRYPT}
};

FieldInfo m_stMwAssignU[AssignUCnt] =
{
{ "job_str_dtm"           , "job_str_dtm"           , SQLITE_STR, DECRYPT},
{ "job_end_dtm"           , "job_end_dtm"           , SQLITE_STR, DECRYPT},
{ "proc_sts_cd"           , "proc_sts_cd"           , SQLITE_STR, DECRYPT},
{ "pda_trans_flag"        , "pda_trans_flag"        , SQLITE_STR, DECRYPT},
{ "pda_num"               , "pda_num"               , SQLITE_STR, DECRYPT},
{ "branch_cd"             , "branch_cd"             , SQLITE_STR, DECRYPT},
{ "center_cd"             , "center_cd"             , SQLITE_STR, DECRYPT},
{ "assign_empid"          , "assign_empid"          , SQLITE_STR, DECRYPT},
{ "reg_flag"              , "reg_flag"              , SQLITE_STR, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "civil_serv_class_cd"   , "civil_serv_class_cd"   , SQLITE_STR, DECRYPT},
{ "civil_serv_class_nm"   , "civil_serv_class_nm"   , SQLITE_STR, DECRYPT},
{ "pda_duty_flag"         , "pda_duty_flag"         , SQLITE_STR, DECRYPT},
{ "pda_duty"              , "pda_duty"              , SQLITE_STR, DECRYPT},
{ "inst_place_num"        , "inst_place_num"        , SQLITE_STR, DECRYPT},
{ "cust_num"              , "cust_num"              , SQLITE_STR, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "req_info_num"          , "req_info_num"          , SQLITE_STR, DECRYPT},
{ "cont_sts_cd"           , "cont_sts_cd"           , SQLITE_STR, DECRYPT},
{ "promise_ymd"           , "promise_ymd"           , SQLITE_STR, DECRYPT},
{ "promise_time"          , "promise_time"          , SQLITE_STR, DECRYPT},
{ "end_expect_time"       , "end_expect_time"       , SQLITE_STR, DECRYPT},
{ "promise_assign_desc"   , "promise_assign_desc"   , SQLITE_STR, DECRYPT},
{ "send_yn"               , "send_yn"               , SQLITE_STR, DECRYPT},
{ "req_tel_ddd"           , "req_tel_ddd"           , SQLITE_STR, DECRYPT},
{ "req_tel_exn"           , "req_tel_exn"           , SQLITE_STR, DECRYPT},
{ "req_tel_num"           , "req_tel_num"           , SQLITE_STR, DECRYPT},
{ "req_cp_ddd"            , "req_cp_ddd"            , SQLITE_STR, DECRYPT},
{ "req_cp_exn"            , "req_cp_exn"            , SQLITE_STR, DECRYPT},
{ "req_cp_num"            , "req_cp_num"            , SQLITE_STR, DECRYPT},
{ "trans_in_cust_nm"      , "trans_in_cust_nm"      , SQLITE_STR, DECRYPT},
{ "trans_in_soc_num"      , "trans_in_soc_num"      , SQLITE_STR, DECRYPT},
{ "trans_in_cust_num"     , "trans_in_cust_num"     , SQLITE_STR, DECRYPT},
{ "req_nm"                , "req_nm"                , SQLITE_STR, DECRYPT},
{ "req_soc_num"           , "req_soc_num"           , SQLITE_STR, DECRYPT},
{ "receive_dtm"           , "receive_dtm"           , SQLITE_STR, DECRYPT},
{ "cust_type_cd"          , "cust_type_cd"          , SQLITE_STR, DECRYPT},
{ "cust_nm"               , "cust_nm"               , SQLITE_STR, DECRYPT},
{ "firm_nm"               , "firm_nm"               , SQLITE_STR, DECRYPT},
{ "soc_num"               , "soc_num"               , SQLITE_STR, DECRYPT},
{ "biz_regi_num"          , "biz_regi_num"          , SQLITE_STR, DECRYPT},
{ "cp_ddd"                , "cp_ddd"                , SQLITE_STR, DECRYPT},
{ "cp_exn"                , "cp_exn"                , SQLITE_STR, DECRYPT},
{ "cp_num"                , "cp_num"                , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_ddd"      , "ownhouse_tel_ddd"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_exn"      , "ownhouse_tel_exn"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_num"      , "ownhouse_tel_num"      , SQLITE_STR, DECRYPT},
{ "firm_tel_ddd"          , "firm_tel_ddd"          , SQLITE_STR, DECRYPT},
{ "firm_tel_exn"          , "firm_tel_exn"          , SQLITE_STR, DECRYPT},
{ "firm_tel_num"          , "firm_tel_num"          , SQLITE_STR, DECRYPT},
{ "scg_relat_cd"          , "scg_relat_cd"          , SQLITE_STR, DECRYPT},
{ "email"                 , "email"                 , SQLITE_STR, DECRYPT},
{ "family_cnt"            , "family_cnt"            , SQLITE_INT, DECRYPT},
{ "cust_trnd_cd"          , "cust_trnd_cd"          , SQLITE_STR, DECRYPT},
{ "built_in_yn"           , "built_in_yn"           , SQLITE_STR, DECRYPT},
{ "square_meter"          , "square_meter"          , SQLITE_STR, DECRYPT},
{ "curr_addr_union"       , "curr_addr_union"       , SQLITE_STR, DECRYPT},
{ "new_addr_union"        , "new_addr_union"        , SQLITE_STR, DECRYPT},
{ "bld_floor"             , "bld_floor"             , SQLITE_STR, DECRYPT},
{ "house_cnt"             , "house_cnt"             , SQLITE_STR, DECRYPT},
{ "etc_addr"              , "etc_addr"              , SQLITE_STR, DECRYPT},
{ "zip_seq"               , "zip_seq"               , SQLITE_STR, DECRYPT},
{ "deadline_flag"         , "deadline_flag"         , SQLITE_STR, DECRYPT},
{ "gmtr_base_day"         , "gmtr_base_day"         , SQLITE_STR, DECRYPT},
{ "zip_no1"               , "zip_no1"               , SQLITE_STR, DECRYPT},
{ "zip_no2"               , "zip_no2"               , SQLITE_STR, DECRYPT},
{ "city"                  , "city"                  , SQLITE_STR, DECRYPT},
{ "county"                , "county"                , SQLITE_STR, DECRYPT},
{ "town"                  , "town"                  , SQLITE_STR, DECRYPT},
{ "village_ri"            , "village_ri"            , SQLITE_STR, DECRYPT},
{ "village"               , "village"               , SQLITE_STR, DECRYPT},
{ "building"              , "building"              , SQLITE_STR, DECRYPT},
{ "addr1_m"               , "addr1_m"               , SQLITE_STR, DECRYPT},
{ "addr1_s"               , "addr1_s"               , SQLITE_STR, DECRYPT},
{ "law_town"              , "law_town"              , SQLITE_STR, DECRYPT},
{ "new_road_nm"           , "new_road_nm"           , SQLITE_STR, DECRYPT},
{ "new_addr_m"            , "new_addr_m"            , SQLITE_STR, DECRYPT},
{ "new_addr_s"            , "new_addr_s"            , SQLITE_STR, DECRYPT},
{ "auto_yn"               , "auto_yn"               , SQLITE_STR, DECRYPT},
{ "price_yn"              , "price_yn"              , SQLITE_STR, DECRYPT},
{ "pay_method"            , "pay_method"            , SQLITE_STR, DECRYPT},
{ "defray_account_num"    , "defray_account_num"    , SQLITE_STR, DECRYPT},
{ "depositor_nm"          , "depositor_nm"          , SQLITE_STR, DECRYPT},
{ "bank_nm"               , "bank_nm"               , SQLITE_STR, DECRYPT},
{ "law_etc_amt"           , "law_etc_amt"           , SQLITE_STR, DECRYPT},
{ "debt_amt"              , "debt_amt"              , SQLITE_STR, DECRYPT},
{ "bill_gubun"            , "bill_gubun"            , SQLITE_STR, DECRYPT},
{ "new_addr_bld_seq"      , "new_addr_bld_seq"      , SQLITE_STR, DECRYPT},
{ "zero_tax_rt_apply_yn"  , "zero_tax_rt_apply_yn"  , SQLITE_STR, DECRYPT},
{ "special_tax_exemp_yn"  , "special_tax_exemp_yn"  , SQLITE_STR, DECRYPT},
{ "trans_conn_yn"         , "trans_conn_yn"       	, SQLITE_STR, DECRYPT},
{ "conn_yn"       		  , "conn_yn"       		, SQLITE_STR, DECRYPT},
{ "bar_gbn"       		  , "bar_gbn"       		, SQLITE_STR, DECRYPT},
{ "bar_yn"       		  , "bar_yn"       			, SQLITE_STR, DECRYPT},
{ "bar_why"       		  , "bar_why"       		, SQLITE_STR, DECRYPT},
{ "chk_yn"       		  , "chk_yn"       			, SQLITE_STR, DECRYPT},
{ "conn_gbn"       		  , "conn_gbn"       		, SQLITE_STR, DECRYPT},
{ "mtr_photo_yn"       	  , "mtr_photo_yn"       	, SQLITE_STR, DECRYPT},
{ "place_photo_yn"        , "place_photo_yn"        , SQLITE_STR, DECRYPT},
{ "social_welf_disc_yn"   , "social_welf_disc_yn"   , SQLITE_STR, DECRYPT},
{ "info_trans_yn"         , "info_trans_yn"         , SQLITE_STR, DECRYPT},
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT}
};
//{ "account"               , "account"               , SQLITE_INT, DECRYPT},
//{ "once_account"          , "once_account"          , SQLITE_INT, DECRYPT},

FieldInfo m_stMwAssignI[AssignICnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "job_str_dtm"           , "job_str_dtm"           , SQLITE_STR, DECRYPT},
{ "job_end_dtm"           , "job_end_dtm"           , SQLITE_STR, DECRYPT},
{ "proc_sts_cd"           , "proc_sts_cd"           , SQLITE_STR, DECRYPT},
{ "pda_trans_flag"        , "pda_trans_flag"        , SQLITE_STR, DECRYPT},
{ "pda_num"               , "pda_num"               , SQLITE_STR, DECRYPT},
{ "branch_cd"             , "branch_cd"             , SQLITE_STR, DECRYPT},
{ "center_cd"             , "center_cd"             , SQLITE_STR, DECRYPT},
{ "assign_empid"          , "assign_empid"          , SQLITE_STR, DECRYPT},
{ "reg_flag"              , "reg_flag"              , SQLITE_STR, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "civil_serv_class_cd"   , "civil_serv_class_cd"   , SQLITE_STR, DECRYPT},
{ "civil_serv_class_nm"   , "civil_serv_class_nm"   , SQLITE_STR, DECRYPT},
{ "pda_duty_flag"         , "pda_duty_flag"         , SQLITE_STR, DECRYPT},
{ "pda_duty"              , "pda_duty"              , SQLITE_STR, DECRYPT},
{ "inst_place_num"        , "inst_place_num"        , SQLITE_STR, DECRYPT},
{ "cust_num"              , "cust_num"              , SQLITE_STR, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "req_info_num"          , "req_info_num"          , SQLITE_STR, DECRYPT},
{ "cont_sts_cd"           , "cont_sts_cd"           , SQLITE_STR, DECRYPT},
{ "promise_ymd"           , "promise_ymd"           , SQLITE_STR, DECRYPT},
{ "promise_time"          , "promise_time"          , SQLITE_STR, DECRYPT},
{ "end_expect_time"       , "end_expect_time"       , SQLITE_STR, DECRYPT},
{ "promise_assign_desc"   , "promise_assign_desc"   , SQLITE_STR, DECRYPT},
{ "account"               , "account"               , SQLITE_INT, DECRYPT},
{ "once_account"          , "once_account"          , SQLITE_INT, DECRYPT},
{ "send_yn"               , "send_yn"               , SQLITE_STR, DECRYPT},
{ "req_tel_ddd"           , "req_tel_ddd"           , SQLITE_STR, DECRYPT},
{ "req_tel_exn"           , "req_tel_exn"           , SQLITE_STR, DECRYPT},
{ "req_tel_num"           , "req_tel_num"           , SQLITE_STR, DECRYPT},
{ "req_cp_ddd"            , "req_cp_ddd"            , SQLITE_STR, DECRYPT},
{ "req_cp_exn"            , "req_cp_exn"            , SQLITE_STR, DECRYPT},
{ "req_cp_num"            , "req_cp_num"            , SQLITE_STR, DECRYPT},
{ "trans_in_cust_nm"      , "trans_in_cust_nm"      , SQLITE_STR, DECRYPT},
{ "trans_in_soc_num"      , "trans_in_soc_num"      , SQLITE_STR, DECRYPT},
{ "trans_in_cust_num"     , "trans_in_cust_num"     , SQLITE_STR, DECRYPT},
{ "req_nm"                , "req_nm"                , SQLITE_STR, DECRYPT},
{ "req_soc_num"           , "req_soc_num"           , SQLITE_STR, DECRYPT},
{ "receive_dtm"           , "receive_dtm"           , SQLITE_STR, DECRYPT},
{ "cust_type_cd"          , "cust_type_cd"          , SQLITE_STR, DECRYPT},
{ "cust_nm"               , "cust_nm"               , SQLITE_STR, DECRYPT},
{ "firm_nm"               , "firm_nm"               , SQLITE_STR, DECRYPT},
{ "soc_num"               , "soc_num"               , SQLITE_STR, DECRYPT},
{ "biz_regi_num"          , "biz_regi_num"          , SQLITE_STR, DECRYPT},
{ "cp_ddd"                , "cp_ddd"                , SQLITE_STR, DECRYPT},
{ "cp_exn"                , "cp_exn"                , SQLITE_STR, DECRYPT},
{ "cp_num"                , "cp_num"                , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_ddd"      , "ownhouse_tel_ddd"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_exn"      , "ownhouse_tel_exn"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_num"      , "ownhouse_tel_num"      , SQLITE_STR, DECRYPT},
{ "firm_tel_ddd"          , "firm_tel_ddd"          , SQLITE_STR, DECRYPT},
{ "firm_tel_exn"          , "firm_tel_exn"          , SQLITE_STR, DECRYPT},
{ "firm_tel_num"          , "firm_tel_num"          , SQLITE_STR, DECRYPT},
{ "scg_relat_cd"          , "scg_relat_cd"          , SQLITE_STR, DECRYPT},
{ "email"                 , "email"                 , SQLITE_STR, DECRYPT},
{ "family_cnt"            , "family_cnt"            , SQLITE_INT, DECRYPT},
{ "cust_trnd_cd"          , "cust_trnd_cd"          , SQLITE_STR, DECRYPT},
{ "built_in_yn"           , "built_in_yn"           , SQLITE_STR, DECRYPT},
{ "square_meter"          , "square_meter"          , SQLITE_STR, DECRYPT},
{ "curr_addr_union"       , "curr_addr_union"       , SQLITE_STR, DECRYPT},
{ "new_addr_union"        , "new_addr_union"        , SQLITE_STR, DECRYPT},
{ "bld_floor"             , "bld_floor"             , SQLITE_STR, DECRYPT},
{ "house_cnt"             , "house_cnt"             , SQLITE_STR, DECRYPT},
{ "etc_addr"              , "etc_addr"              , SQLITE_STR, DECRYPT},
{ "zip_seq"               , "zip_seq"               , SQLITE_STR, DECRYPT},
{ "deadline_flag"         , "deadline_flag"         , SQLITE_STR, DECRYPT},
{ "gmtr_base_day"         , "gmtr_base_day"         , SQLITE_STR, DECRYPT},
{ "zip_no1"               , "zip_no1"               , SQLITE_STR, DECRYPT},
{ "zip_no2"               , "zip_no2"               , SQLITE_STR, DECRYPT},
{ "city"                  , "city"                  , SQLITE_STR, DECRYPT},
{ "county"                , "county"                , SQLITE_STR, DECRYPT},
{ "town"                  , "town"                  , SQLITE_STR, DECRYPT},
{ "village_ri"            , "village_ri"            , SQLITE_STR, DECRYPT},
{ "village"               , "village"               , SQLITE_STR, DECRYPT},
{ "building"              , "building"              , SQLITE_STR, DECRYPT},
{ "addr1_m"               , "addr1_m"               , SQLITE_STR, DECRYPT},
{ "addr1_s"               , "addr1_s"               , SQLITE_STR, DECRYPT},
{ "law_town"              , "law_town"              , SQLITE_STR, DECRYPT},
{ "new_road_nm"           , "new_road_nm"           , SQLITE_STR, DECRYPT},
{ "new_addr_m"            , "new_addr_m"            , SQLITE_STR, DECRYPT},
{ "new_addr_s"            , "new_addr_s"            , SQLITE_STR, DECRYPT},
{ "auto_yn"               , "auto_yn"               , SQLITE_STR, DECRYPT},
{ "price_yn"              , "price_yn"              , SQLITE_STR, DECRYPT},
{ "pay_method"            , "pay_method"            , SQLITE_STR, DECRYPT},
{ "defray_account_num"    , "defray_account_num"    , SQLITE_STR, DECRYPT},
{ "depositor_nm"          , "depositor_nm"          , SQLITE_STR, DECRYPT},
{ "bank_nm"               , "bank_nm"               , SQLITE_STR, DECRYPT},
{ "law_etc_amt"           , "law_etc_amt"           , SQLITE_STR, DECRYPT},
{ "debt_amt"              , "debt_amt"              , SQLITE_STR, DECRYPT},
{ "bill_gubun"            , "bill_gubun"            , SQLITE_STR, DECRYPT},
{ "new_addr_bld_seq"      , "new_addr_bld_seq"      , SQLITE_STR, DECRYPT},
{ "zero_tax_rt_apply_yn"  , "zero_tax_rt_apply_yn"  , SQLITE_STR, DECRYPT},
{ "special_tax_exemp_yn"  , "special_tax_exemp_yn"  , SQLITE_STR, DECRYPT},
{ "get_spc_tax_chk"       , "get_spc_tax_chk"       , SQLITE_STR, DECRYPT},
{ "trans_conn_yn"         , "trans_conn_yn"       	, SQLITE_STR, DECRYPT},
{ "conn_yn"       		  , "conn_yn"       		, SQLITE_STR, DECRYPT},
{ "bar_gbn"       		  , "bar_gbn"       		, SQLITE_STR, DECRYPT},
{ "bar_yn"       		  , "bar_yn"       			, SQLITE_STR, DECRYPT},
{ "bar_why"       		  , "bar_why"       		, SQLITE_STR, DECRYPT},
{ "chk_yn"       		  , "chk_yn"       			, SQLITE_STR, DECRYPT},
{ "conn_gbn"       		  , "conn_gbn"       		, SQLITE_STR, DECRYPT},
{ "mtr_photo_yn"       	  , "mtr_photo_yn"       	, SQLITE_STR, DECRYPT},
{ "place_photo_yn"        , "place_photo_yn"        , SQLITE_STR, DECRYPT},
{ "social_welf_disc_yn"   , "social_welf_disc_yn"   , SQLITE_STR, DECRYPT},
{ "info_trans_yn"         , "info_trans_yn"         , SQLITE_STR, DECRYPT}
};

#define MtrKeyCnt 	2
#define MtrUCnt 	61
#define MtrICnt 	61

FieldInfo m_stMwMtrKey[MtrKeyCnt] =
{
 { "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
 { "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
};

FieldInfo m_stMwMtrU[MtrUCnt] =
{
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "inst_place_num"        , "inst_place_num"        , SQLITE_STR, DECRYPT},
{ "bill_gubun"            , "bill_gubun"            , SQLITE_STR, DECRYPT},
{ "mtr_id_num"            , "mtr_id_num"            , SQLITE_STR, DECRYPT},
{ "mtr_grd"               , "mtr_grd"               , SQLITE_STR, DECRYPT},
{ "mtr_form"              , "mtr_form"              , SQLITE_STR, DECRYPT},
{ "mtr_form_nm"           , "mtr_form_nm"           , SQLITE_STR, DECRYPT},
{ "mtr_type"              , "mtr_type"              , SQLITE_STR, DECRYPT},
{ "mtr_type_nm"           , "mtr_type_nm"           , SQLITE_STR, DECRYPT},
{ "mtr_remote_flag"       , "mtr_remote_flag"       , SQLITE_STR, DECRYPT},
{ "mtr_remote_flag_nm"    , "mtr_remote_flag_nm"    , SQLITE_STR, DECRYPT},
{ "mtr_kind"              , "mtr_kind"              , SQLITE_STR, DECRYPT},
{ "mtr_kind_nm"           , "mtr_kind_nm"           , SQLITE_STR, DECRYPT},
{ "mtr_digit_cnt"         , "mtr_digit_cnt"         , SQLITE_INT, DECRYPT},
{ "mtr_new_fix_flag"      , "mtr_new_fix_flag"      , SQLITE_STR, DECRYPT},
{ "mtr_valid_ym"          , "mtr_valid_ym"          , SQLITE_STR, DECRYPT},
{ "mtr_appro_yn"          , "mtr_appro_yn"          , SQLITE_STR, DECRYPT},
{ "sealed_ymd"            , "sealed_ymd"            , SQLITE_STR, DECRYPT},
{ "sealed_sts"            , "sealed_sts"            , SQLITE_STR, DECRYPT},
{ "chk_bar_adhere_ymd"    , "chk_bar_adhere_ymd"    , SQLITE_STR, DECRYPT},
{ "chk_bar_adhere_sts"    , "chk_bar_adhere_sts"    , SQLITE_STR, DECRYPT},
{ "mtr_deta_loc"          , "mtr_deta_loc"          , SQLITE_STR, DECRYPT},
{ "keeper_yn"             , "keeper_yn"             , SQLITE_STR, DECRYPT},
{ "revis_flag"            , "revis_flag"            , SQLITE_STR, DECRYPT},
{ "mtr_loc_flag"          , "mtr_loc_flag"          , SQLITE_STR, DECRYPT},
{ "mtr_loc_flag_nm"       , "mtr_loc_flag_nm"       , SQLITE_STR, DECRYPT},
{ "mtr_inst_height"       , "mtr_inst_height"       , SQLITE_STR, DECRYPT},
{ "mtr_resou_flag"        , "mtr_resou_flag"        , SQLITE_STR, DECRYPT},
{ "mtr_supply_sts"        , "mtr_supply_sts"        , SQLITE_STR, DECRYPT},
{ "mtr_supply_sts_nm"     , "mtr_supply_sts_nm"     , SQLITE_STR, DECRYPT},
{ "mtr_model_cd"          , "mtr_model_cd"          , SQLITE_STR, DECRYPT},
{ "mtr_model_nm"          , "mtr_model_nm"          , SQLITE_STR, DECRYPT},
{ "compens_model_nm"      , "compens_model_nm"      , SQLITE_STR, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "prod_cont_seq"         , "prod_cont_seq"         , SQLITE_STR, DECRYPT},
{ "prod_cont_ymd"         , "prod_cont_ymd"         , SQLITE_STR, DECRYPT},
{ "biz_type_cd"           , "biz_type_cd"           , SQLITE_STR, DECRYPT},
{ "prod_cd"               , "prod_cd"               , SQLITE_STR, DECRYPT},
{ "prod_nm"               , "prod_nm"               , SQLITE_STR, DECRYPT},
{ "prod_area_flag"        , "prod_area_flag"        , SQLITE_STR, DECRYPT},
{ "cont_flag_cd"          , "cont_flag_cd"          , SQLITE_STR, DECRYPT},
{ "prod_sts_cd"           , "prod_sts_cd"           , SQLITE_STR, DECRYPT},
{ "cont_revis_para"       , "cont_revis_para"       , SQLITE_INT, DECRYPT},
{ "cut_ymd"               , "cut_ymd"               , SQLITE_STR, DECRYPT},
{ "cut_type_cd"           , "cut_type_cd"           , SQLITE_STR, DECRYPT},
{ "cut_treat_empid"       , "cut_treat_empid"       , SQLITE_STR, DECRYPT},
{ "cut_why_cd"            , "cut_why_cd"            , SQLITE_STR, DECRYPT},
{ "cut_cnl_ymd"           , "cut_cnl_ymd"           , SQLITE_STR, DECRYPT},
{ "indi_cut_vc_after"     , "indi_cut_vc_after"     , SQLITE_INT, DECRYPT},
{ "indi_cut_va_after"     , "indi_cut_va_after"     , SQLITE_INT, DECRYPT},
{ "indi_cut_vm_after"     , "indi_cut_vm_after"     , SQLITE_INT, DECRYPT},
{ "indi_cut_ymd"          , "indi_cut_ymd"          , SQLITE_STR, DECRYPT},
{ "indi_type_cd"          , "indi_type_cd"          , SQLITE_STR, DECRYPT},
{ "indi_type_nm"          , "indi_type_nm"          , SQLITE_STR, DECRYPT},
{ "indi_vc_after"         , "indi_vc_after"         , SQLITE_INT, DECRYPT},
{ "indi_va_after"         , "indi_va_after"         , SQLITE_INT, DECRYPT},
{ "indi_vm_after"         , "indi_vm_after"         , SQLITE_INT, DECRYPT},
{ "fix_firm_nm_cd"        , "fix_firm_nm_cd"        , SQLITE_STR, DECRYPT},
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT}

};

FieldInfo m_stMwMtrI[MtrICnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "inst_place_num"        , "inst_place_num"        , SQLITE_STR, DECRYPT},
{ "bill_gubun"            , "bill_gubun"            , SQLITE_STR, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
{ "mtr_id_num"            , "mtr_id_num"            , SQLITE_STR, DECRYPT},
{ "mtr_grd"               , "mtr_grd"               , SQLITE_STR, DECRYPT},
{ "mtr_form"              , "mtr_form"              , SQLITE_STR, DECRYPT},
{ "mtr_form_nm"           , "mtr_form_nm"           , SQLITE_STR, DECRYPT},
{ "mtr_type"              , "mtr_type"              , SQLITE_STR, DECRYPT},
{ "mtr_type_nm"           , "mtr_type_nm"           , SQLITE_STR, DECRYPT},
{ "mtr_remote_flag"       , "mtr_remote_flag"       , SQLITE_STR, DECRYPT},
{ "mtr_remote_flag_nm"    , "mtr_remote_flag_nm"    , SQLITE_STR, DECRYPT},
{ "mtr_kind"              , "mtr_kind"              , SQLITE_STR, DECRYPT},
{ "mtr_kind_nm"           , "mtr_kind_nm"           , SQLITE_STR, DECRYPT},
{ "mtr_digit_cnt"         , "mtr_digit_cnt"         , SQLITE_INT, DECRYPT},
{ "mtr_new_fix_flag"      , "mtr_new_fix_flag"      , SQLITE_STR, DECRYPT},
{ "mtr_valid_ym"          , "mtr_valid_ym"          , SQLITE_STR, DECRYPT},
{ "mtr_appro_yn"          , "mtr_appro_yn"          , SQLITE_STR, DECRYPT},
{ "sealed_ymd"            , "sealed_ymd"            , SQLITE_STR, DECRYPT},
{ "sealed_sts"            , "sealed_sts"            , SQLITE_STR, DECRYPT},
{ "chk_bar_adhere_ymd"    , "chk_bar_adhere_ymd"    , SQLITE_STR, DECRYPT},
{ "chk_bar_adhere_sts"    , "chk_bar_adhere_sts"    , SQLITE_STR, DECRYPT},
{ "mtr_deta_loc"          , "mtr_deta_loc"          , SQLITE_STR, DECRYPT},
{ "keeper_yn"             , "keeper_yn"             , SQLITE_STR, DECRYPT},
{ "revis_flag"            , "revis_flag"            , SQLITE_STR, DECRYPT},
{ "mtr_loc_flag"          , "mtr_loc_flag"          , SQLITE_STR, DECRYPT},
{ "mtr_loc_flag_nm"       , "mtr_loc_flag_nm"       , SQLITE_STR, DECRYPT},
{ "mtr_inst_height"       , "mtr_inst_height"       , SQLITE_STR, DECRYPT},
{ "mtr_resou_flag"        , "mtr_resou_flag"        , SQLITE_STR, DECRYPT},
{ "mtr_supply_sts"        , "mtr_supply_sts"        , SQLITE_STR, DECRYPT},
{ "mtr_supply_sts_nm"     , "mtr_supply_sts_nm"     , SQLITE_STR, DECRYPT},
{ "mtr_model_cd"          , "mtr_model_cd"          , SQLITE_STR, DECRYPT},
{ "mtr_model_nm"          , "mtr_model_nm"          , SQLITE_STR, DECRYPT},
{ "compens_model_nm"      , "compens_model_nm"      , SQLITE_STR, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "prod_cont_seq"         , "prod_cont_seq"         , SQLITE_STR, DECRYPT},
{ "prod_cont_ymd"         , "prod_cont_ymd"         , SQLITE_STR, DECRYPT},
{ "biz_type_cd"           , "biz_type_cd"           , SQLITE_STR, DECRYPT},
{ "prod_cd"               , "prod_cd"               , SQLITE_STR, DECRYPT},
{ "prod_nm"               , "prod_nm"               , SQLITE_STR, DECRYPT},
{ "prod_area_flag"        , "prod_area_flag"        , SQLITE_STR, DECRYPT},
{ "cont_flag_cd"          , "cont_flag_cd"          , SQLITE_STR, DECRYPT},
{ "prod_sts_cd"           , "prod_sts_cd"           , SQLITE_STR, DECRYPT},
{ "cont_revis_para"       , "cont_revis_para"       , SQLITE_STR, DECRYPT},
{ "cut_ymd"               , "cut_ymd"               , SQLITE_STR, DECRYPT},
{ "cut_type_cd"           , "cut_type_cd"           , SQLITE_STR, DECRYPT},
{ "cut_treat_empid"       , "cut_treat_empid"       , SQLITE_STR, DECRYPT},
{ "cut_why_cd"            , "cut_why_cd"            , SQLITE_STR, DECRYPT},
{ "cut_cnl_ymd"           , "cut_cnl_ymd"           , SQLITE_STR, DECRYPT},
{ "indi_cut_vc_after"     , "indi_cut_vc_after"     , SQLITE_INT, DECRYPT},
{ "indi_cut_va_after"     , "indi_cut_va_after"     , SQLITE_INT, DECRYPT},
{ "indi_cut_vm_after"     , "indi_cut_vm_after"     , SQLITE_INT, DECRYPT},
{ "indi_cut_ymd"          , "indi_cut_ymd"          , SQLITE_STR, DECRYPT},
{ "indi_type_cd"          , "indi_type_cd"          , SQLITE_STR, DECRYPT},
{ "indi_type_nm"          , "indi_type_nm"          , SQLITE_STR, DECRYPT},
{ "indi_vc_after"         , "indi_vc_after"         , SQLITE_INT, DECRYPT},
{ "indi_va_after"         , "indi_va_after"         , SQLITE_INT, DECRYPT},
{ "indi_vm_after"         , "indi_vm_after"         , SQLITE_INT, DECRYPT},
{ "fix_firm_nm_cd"        , "fix_firm_nm_cd"        , SQLITE_STR, DECRYPT}

};

#define BurKeyCnt 	3
#define BurUCnt 	31
#define BurICnt 	31

FieldInfo m_stMwBurKey[BurKeyCnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
{ "burner_num"            , "burner_num"            , SQLITE_STR, DECRYPT}
};

FieldInfo m_stMwBurU[BurUCnt] =
{
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "inst_place_num"        , "inst_place_num"        , SQLITE_STR, DECRYPT},
{ "mtr_id_num"            , "mtr_id_num"            , SQLITE_STR, DECRYPT},
{ "burner_class_cd"       , "burner_class_cd"       , SQLITE_STR, DECRYPT},
{ "burner_kind_num"       , "burner_kind_num"       , SQLITE_STR, DECRYPT},
{ "burner_kind_nm"        , "burner_kind_nm"        , SQLITE_STR, DECRYPT},
{ "burner_model_cd"       , "burner_model_cd"       , SQLITE_STR, DECRYPT},
{ "burner_capa"           , "burner_capa"           , SQLITE_INT, DECRYPT},
{ "burner_capa_unit"      , "burner_capa_unit"      , SQLITE_STR, DECRYPT},
{ "burner_capa_unit_nm"   , "burner_capa_unit_nm"   , SQLITE_STR, DECRYPT},
{ "burner_inst_ymd"       , "burner_inst_ymd"       , SQLITE_STR, DECRYPT},
{ "burner_remov_ymd"      , "burner_remov_ymd"      , SQLITE_STR, DECRYPT},
{ "burner_model_nm"       , "burner_model_nm"       , SQLITE_STR, DECRYPT},
{ "burner_qty"            , "burner_qty"            , SQLITE_INT, DECRYPT},
{ "maker_nm"              , "maker_nm"              , SQLITE_STR, DECRYPT},
{ "maker_num"             , "maker_num"             , SQLITE_STR, DECRYPT},
{ "boiler_form"           , "boiler_form"           , SQLITE_STR, DECRYPT},
{ "boiler_form_nm"        , "boiler_form_nm"        , SQLITE_STR, DECRYPT},
{ "make_num"              , "make_num"              , SQLITE_STR, DECRYPT},
{ "make_ymd"              , "make_ymd"              , SQLITE_STR, DECRYPT},
{ "work_docu_receive_ymd" , "work_docu_receive_ymd" , SQLITE_STR, DECRYPT},
{ "inst_flag"             , "inst_flag"             , SQLITE_STR, DECRYPT},
{ "inst_loc"              , "inst_loc"              , SQLITE_STR, DECRYPT},
{ "inst_loc_nm"           , "inst_loc_nm"           , SQLITE_STR, DECRYPT},
{ "boiler_inst_firm_cd"   , "boiler_inst_firm_cd"   , SQLITE_STR, DECRYPT},
{ "boiler_inst_firm_nm"   , "boiler_inst_firm_nm"   , SQLITE_STR, DECRYPT},
{ "special_yn"            , "special_yn"            , SQLITE_STR, DECRYPT},
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
{ "burner_num"            , "burner_num"            , SQLITE_STR, DECRYPT}
};

FieldInfo m_stMwBurI[BurICnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
{ "burner_num"            , "burner_num"            , SQLITE_STR, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "inst_place_num"        , "inst_place_num"        , SQLITE_STR, DECRYPT},
{ "mtr_id_num"            , "mtr_id_num"            , SQLITE_STR, DECRYPT},
{ "burner_class_cd"       , "burner_class_cd"       , SQLITE_STR, DECRYPT},
{ "burner_kind_num"       , "burner_kind_num"       , SQLITE_STR, DECRYPT},
{ "burner_kind_nm"        , "burner_kind_nm"        , SQLITE_STR, DECRYPT},
{ "burner_model_cd"       , "burner_model_cd"       , SQLITE_STR, DECRYPT},
{ "burner_capa"           , "burner_capa"           , SQLITE_INT, DECRYPT},
{ "burner_capa_unit"      , "burner_capa_unit"      , SQLITE_STR, DECRYPT},
{ "burner_capa_unit_nm"   , "burner_capa_unit_nm"   , SQLITE_STR, DECRYPT},
{ "burner_inst_ymd"       , "burner_inst_ymd"       , SQLITE_STR, DECRYPT},
{ "burner_remov_ymd"      , "burner_remov_ymd"      , SQLITE_STR, DECRYPT},
{ "burner_model_nm"       , "burner_model_nm"       , SQLITE_STR, DECRYPT},
{ "burner_qty"            , "burner_qty"            , SQLITE_INT, DECRYPT},
{ "maker_nm"              , "maker_nm"              , SQLITE_STR, DECRYPT},
{ "maker_num"             , "maker_num"             , SQLITE_STR, DECRYPT},
{ "boiler_form"           , "boiler_form"           , SQLITE_STR, DECRYPT},
{ "boiler_form_nm"        , "boiler_form_nm"        , SQLITE_STR, DECRYPT},
{ "make_num"              , "make_num"              , SQLITE_STR, DECRYPT},
{ "make_ymd"              , "make_ymd"              , SQLITE_STR, DECRYPT},
{ "work_docu_receive_ymd" , "work_docu_receive_ymd" , SQLITE_STR, DECRYPT},
{ "inst_flag"             , "inst_flag"             , SQLITE_STR, DECRYPT},
{ "inst_loc"              , "inst_loc"              , SQLITE_STR, DECRYPT},
{ "inst_loc_nm"           , "inst_loc_nm"           , SQLITE_STR, DECRYPT},
{ "boiler_inst_firm_cd"   , "boiler_inst_firm_cd"   , SQLITE_STR, DECRYPT},
{ "boiler_inst_firm_nm"   , "boiler_inst_firm_nm"   , SQLITE_STR, DECRYPT},
{ "special_yn"            , "special_yn"            , SQLITE_STR, DECRYPT}
};

#define CustKeyCnt 	1
#define CustUCnt 	29
#define CustICnt 	29

FieldInfo m_stMwCustKey[CustKeyCnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT}
};

FieldInfo m_stMwCustU[CustUCnt] =
{
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "cnt"                   , "cnt"                   , SQLITE_INT, DECRYPT},
{ "unpay_amt"             , "unpay_amt"             , SQLITE_INT, DECRYPT},
{ "cust_num"              , "cust_num"              , SQLITE_STR, DECRYPT},
{ "cust_type_cd"          , "cust_type_cd"          , SQLITE_STR, DECRYPT},
{ "cust_nm"               , "cust_nm"               , SQLITE_STR, DECRYPT},
{ "firm_nm"               , "firm_nm"               , SQLITE_STR, DECRYPT},
{ "soc_num"               , "soc_num"               , SQLITE_STR, DECRYPT},
{ "biz_regi_num"          , "biz_regi_num"          , SQLITE_STR, DECRYPT},
{ "cp_ddd"                , "cp_ddd"                , SQLITE_STR, DECRYPT},
{ "cp_exn"                , "cp_exn"                , SQLITE_STR, DECRYPT},
{ "cp_num"                , "cp_num"                , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_ddd"      , "ownhouse_tel_ddd"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_exn"      , "ownhouse_tel_exn"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_num"      , "ownhouse_tel_num"      , SQLITE_STR, DECRYPT},
{ "firm_tel_ddd"          , "firm_tel_ddd"          , SQLITE_STR, DECRYPT},
{ "firm_tel_exn"          , "firm_tel_exn"          , SQLITE_STR, DECRYPT},
{ "firm_tel_num"          , "firm_tel_num"          , SQLITE_STR, DECRYPT},
{ "scg_relat_cd"          , "scg_relat_cd"          , SQLITE_STR, DECRYPT},
{ "email"                 , "email"                 , SQLITE_STR, DECRYPT},
{ "family_cnt"            , "family_cnt"            , SQLITE_INT, DECRYPT},
{ "cust_trnd_cd"          , "cust_trnd_cd"          , SQLITE_STR, DECRYPT},
{ "defray_account_num"    , "defray_account_num"    , SQLITE_STR, DECRYPT},
{ "depositor_nm"          , "depositor_nm"          , SQLITE_STR, DECRYPT},
{ "req_info_num"          , "req_info_num"          , SQLITE_STR, DECRYPT},
{ "bank_nm"               , "bank_nm"               , SQLITE_STR, DECRYPT},
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT}
};

FieldInfo m_stMwCustI[CustICnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "cnt"                   , "cnt"                   , SQLITE_INT, DECRYPT},
{ "unpay_amt"             , "unpay_amt"             , SQLITE_INT, DECRYPT},
{ "cust_num"              , "cust_num"              , SQLITE_STR, DECRYPT},
{ "cust_type_cd"          , "cust_type_cd"          , SQLITE_STR, DECRYPT},
{ "cust_nm"               , "cust_nm"               , SQLITE_STR, DECRYPT},
{ "firm_nm"               , "firm_nm"               , SQLITE_STR, DECRYPT},
{ "soc_num"               , "soc_num"               , SQLITE_STR, DECRYPT},
{ "biz_regi_num"          , "biz_regi_num"          , SQLITE_STR, DECRYPT},
{ "cp_ddd"                , "cp_ddd"                , SQLITE_STR, DECRYPT},
{ "cp_exn"                , "cp_exn"                , SQLITE_STR, DECRYPT},
{ "cp_num"                , "cp_num"                , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_ddd"      , "ownhouse_tel_ddd"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_exn"      , "ownhouse_tel_exn"      , SQLITE_STR, DECRYPT},
{ "ownhouse_tel_num"      , "ownhouse_tel_num"      , SQLITE_STR, DECRYPT},
{ "firm_tel_ddd"          , "firm_tel_ddd"          , SQLITE_STR, DECRYPT},
{ "firm_tel_exn"          , "firm_tel_exn"          , SQLITE_STR, DECRYPT},
{ "firm_tel_num"          , "firm_tel_num"          , SQLITE_STR, DECRYPT},
{ "scg_relat_cd"          , "scg_relat_cd"          , SQLITE_STR, DECRYPT},
{ "email"                 , "email"                 , SQLITE_STR, DECRYPT},
{ "family_cnt"            , "family_cnt"            , SQLITE_INT, DECRYPT},
{ "cust_trnd_cd"          , "cust_trnd_cd"          , SQLITE_STR, DECRYPT},
{ "defray_account_num"    , "defray_account_num"    , SQLITE_STR, DECRYPT},
{ "depositor_nm"          , "depositor_nm"          , SQLITE_STR, DECRYPT},
{ "req_info_num"          , "req_info_num"          , SQLITE_STR, DECRYPT},
{ "bank_nm"               , "bank_nm"               , SQLITE_STR, DECRYPT}
};


#define NonpayKeyCnt 	6
#define NonpayUCnt 		16
#define NonpayICnt 		16

FieldInfo m_stMwNospayKey[NonpayKeyCnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
{ "req_ym"                , "req_ym"                , SQLITE_STR, DECRYPT}
};

FieldInfo m_stMwNospayU[NonpayUCnt] =
{
{ "deadline_flag"         , "deadline_flag"         , SQLITE_STR, DECRYPT},
{ "prod_cont_seq"         , "prod_cont_seq"         , SQLITE_STR, DECRYPT},
{ "use_qty"               , "use_qty"               , SQLITE_INT, DECRYPT},
{ "indi_compens_vc"       , "indi_compens_vc"       , SQLITE_INT, DECRYPT},
{ "subtr_req_amt"         , "subtr_req_amt"         , SQLITE_INT, DECRYPT},
{ "unpay_amt"             , "unpay_amt"             , SQLITE_INT, DECRYPT},
{ "center_cd"             , "center_cd"             , SQLITE_STR, DECRYPT},
{ "use_period_str"        , "use_period_str"        , SQLITE_STR, DECRYPT},
{ "use_period_end"        , "use_period_end"        , SQLITE_STR, DECRYPT},
{ "req_manage_sts"        , "req_manage_sts"        , SQLITE_STR, DECRYPT},
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
{ "req_ym"                , "req_ym"                , SQLITE_STR, DECRYPT}

};

FieldInfo m_stMwNospayI[NonpayICnt] =
{
{ "promise_assign_seq"    , "promise_assign_seq"    , SQLITE_INT, DECRYPT},
{ "civil_serv_receive_num", "civil_serv_receive_num", SQLITE_STR, DECRYPT},
{ "treat_seq"             , "treat_seq"             , SQLITE_INT, DECRYPT},
{ "prod_cont_seq"         , "prod_cont_seq"         , SQLITE_STR, DECRYPT},
{ "use_cont_num"          , "use_cont_num"          , SQLITE_STR, DECRYPT},
{ "mtr_num"               , "mtr_num"               , SQLITE_STR, DECRYPT},
{ "req_ym"                , "req_ym"                , SQLITE_STR, DECRYPT},
{ "deadline_flag"         , "deadline_flag"         , SQLITE_STR, DECRYPT},
{ "use_qty"               , "use_qty"               , SQLITE_INT, DECRYPT},
{ "indi_compens_vc"       , "indi_compens_vc"       , SQLITE_INT, DECRYPT},
{ "subtr_req_amt"         , "subtr_req_amt"         , SQLITE_INT, DECRYPT},
{ "unpay_amt"             , "unpay_amt"             , SQLITE_INT, DECRYPT},
{ "center_cd"             , "center_cd"             , SQLITE_STR, DECRYPT},
{ "use_period_str"        , "use_period_str"        , SQLITE_STR, DECRYPT},
{ "use_period_end"        , "use_period_end"        , SQLITE_STR, DECRYPT},
{ "req_manage_sts"        , "req_manage_sts"        , SQLITE_STR, DECRYPT}
};


#endif

